"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
require("dotenv/config");
var user_router_js_1 = require("./routes/user-router.js");
var climb_router_js_1 = require("./routes/climb-router.js");
var morgan_js_1 = require("./config/loggers/morgan.js");
var winston_js_1 = require("./config/loggers/winston.js");
var ErrorHandler_js_1 = require("./middleware/ErrorHandler.js");
var passport_js_1 = require("./config/auth/passport.js");
var cors_1 = require("cors");
var app = (0, express_1.default)();
app.use((0, cors_1.default)());
app.use(express_1.default.json());
app.use(morgan_js_1.default);
app.use('/', user_router_js_1.default);
app.use('/climbs', passport_js_1.default.authenticate('jwt', { session: false }), climb_router_js_1.default);
app.use(ErrorHandler_js_1.default);
app.listen(process.env.SERVER_PORT || 3000, function () {
    winston_js_1.default.info("Server is running on port ".concat(process.env.PORT || 3000));
});
